### ISSUE TITLE
Bing Ads PPC Conversion Tracking Code

### ISSUE THREAD

**Issue by annabhill** [icrunchdata/development#209]
- Need to add Bing Ads conversion tracking code to every page of website. This code works differently than the Google AdWords code in that it needs to be placed on every page of the site, rather than only on the confirmation page.  This code should be placed above the </body> tag on all pages. See code atttached.

[bing-ads-conversion-tracking.txt](https://github.com/icrunchdata/development/files/715335/bing-ads-conversion-tracking.txt)

**Comment by rtemery** [comment]
My response:

Although this is not particularly difficult to do (can be pasted on master page template), since we are not launching Bing Ads at this time; we feel it would be better to wait on this until such time that are ready to test Bing Ads.  This follows our protocol of JIT (just in time) development practices.

**Comment by rtemery** [comment]
This makes no sense, as even Ian said we wouldn't do Bing ads until Google was saturated (that's a long time off).

Closed.
