### ISSUE TITLE
SEO Ecommerce Tracking Configuration

### ISSUE THREAD

**Issue by annabhill** [icrunchdata/development#211]
Instructions for this can be found here: https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce

The main piece of this is the "Adding a Transaction" section. That is really the only data SN needs.

**Comment by rtemery** [comment]
I've already researched this in 2016. The implementation is quite invasive, and requires a deep-dive into Woocommerce + Google Analytics shopping cart values.  I think Woocommerce sells a premium plugin for this integration.  However, since 98% of our transactions are $375, it makes more sense for us to use that static value in Google Universal Analytics Goal Tracking.

**Comment by rtemery** [comment]
Their link and instructions make no sense.  I'm closing this.
